### ISSUE TITLE
[BUG] Using  @profile decorator fails  with "TypeError: 'module' object is not callable" in most files in my project

### ISSUE THREAD

**Issue by raphaelTrench** [pyutils/line_profiler#122]
Hello, I have been having an issue running line-profiler via  the built-in injection option with  `kernprof`. On very few files it works,  but on most I get this error no matter what function I  decorate, giving me the error`TypeError: 'module' object is not callable`:

example code:

```python
@profile
def return_1():
    return 1
```

When calling
```bash
└─[$] <git:(development*)> kernprof -l -v -b hermod_profile.py                                                                         <aws:aws>
Wrote profile results to hermod_profile.py.lprof
Timer unit: 1e-06 s
```
```python
Traceback (most recent call last):
  File "/Users/c91195a/Library/Caches/pypoetry/virtualenvs/hermod--2c4GB31-py3.9/bin/kernprof", line 8, in <module>
    sys.exit(main())
  File "/Users/c91195a/Library/Caches/pypoetry/virtualenvs/hermod--2c4GB31-py3.9/lib/python3.9/site-packages/kernprof.py", line 219, in main
    execfile(script_file, ns, ns)
  File "/Users/c91195a/Library/Caches/pypoetry/virtualenvs/hermod--2c4GB31-py3.9/lib/python3.9/site-packages/kernprof.py", line 28, in execfile
    exec(compile(f.read(), filename, 'exec'), globals, locals)
  File "hermod_profile.py", line 1, in <module>
    from hermod.batch import batch
  File "/Users/c91195a/Documents/experian/hermod/hermod/batch.py", line 12, in <module>
    from hermod.executor.batch_executor import BatchExecutor
  File "/Users/c91195a/Documents/experian/hermod/hermod/executor/batch_executor.py", line 3, in <module>
    from hermod.executor.bare_executor import BareExecutor
  File "/Users/c91195a/Documents/experian/hermod/hermod/executor/bare_executor.py", line 32, in <module>
    def return_1():
TypeError: 'module' object is not callable
```

However on some files it works fine,  and if on the ones that dont work I manually override the built-in and use another name for it:

```python
import line_profiler

prof = line_profiler.LineProfiler()
builtins.__dict__["line_prof"] = prof


@line_prof
def return_1():
    return 1
```

I can sucessfully see an output: 

```
bash
Timer unit: 1e-06 s

Total time: 5e-06 s
File: /Users/c91195a/Documents/experian/hermod/hermod/executor/bare_executor.py
Function: return_1 at line 31

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    31                                           @line_prof
    32                                           def return_1():
    33         1          5.0      5.0    100.0      return 1
```

In addition, if I try to override using the same name "profile" then it also doesnt work...

This  error happened both in my local environment, using MacOS 11.6.3 using python 3.9 and inside a docker extending `python:3.8-buster`.
I am using poetry to manage my environment, although even installing line_profiler with pip the same error happened.
Since it works on some files and not others I think it might be something  to do with my code, if thats the case, could anyone please give me some tips on how to find the problem?

**Comment by raphaelTrench** [comment]
> Running `kernprof` will automatically add `profile` to builtins, so maybe that's what happened?

Yes, since  I dont have to import it, my IDE was importing the "profile" module automatically, and thus overriding `kernprof`'s  `profile`
