### ISSUE TITLE
pip install fails however conda install succeeds

### ISSUE THREAD

**Issue by cjproud** [pyutils/line_profiler#204]
An issue has just popped up for me trying to install `line_profiler` on my M1 Mac:

```
$ pip install -v line_profiler==4.0.2


Using pip 23.0.1 from /Users/272393a/opt/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
Collecting line_profiler==4.0.2
  Using cached line_profiler-4.0.2.tar.gz (151 kB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=41.0.1
    Using cached setuptools-67.4.0-py3-none-any.whl (1.1 MB)
  Collecting Cython>=3.0.0a11
    Using cached Cython-3.0.0b1-py2.py3-none-any.whl (1.1 MB)
  Installing collected packages: setuptools, Cython
  Successfully installed Cython-3.0.0b1 setuptools-67.4.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel

  Error compiling Cython file:
  ------------------------------------------------------------
  ...

      def __exit__(self, exc_type, exc_val, exc_tb):
          self.disable_by_count()

      def enable(self):
          PyEval_SetTrace(python_trace_callback, self)
                          ^
  ------------------------------------------------------------

  line_profiler/_line_profiler.pyx:275:24: Cannot assign type 'int (object, PyFrameObject *, int, PyObject *) except? -1' to 'Py_tracefunc'
  Compiling line_profiler/_line_profiler.pyx because it changed.
  [1/1] Cythonizing line_profiler/_line_profiler.pyx
  Traceback (most recent call last):
    File "/Users/272393a/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/272393a/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/272393a/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/xd/dxw2zg2j0l11wb3md3x_qcvjnnqqhb/T/pip-build-env-586ggtti/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/xd/dxw2zg2j0l11wb3md3x_qcvjnnqqhb/T/pip-build-env-586ggtti/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/xd/dxw2zg2j0l11wb3md3x_qcvjnnqqhb/T/pip-build-env-586ggtti/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 235, in <module>
    File "<string>", line 222, in run_cythonize
    File "/private/var/folders/xd/dxw2zg2j0l11wb3md3x_qcvjnnqqhb/T/pip-build-env-586ggtti/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
      cythonize_one(*args)
    File "/private/var/folders/xd/dxw2zg2j0l11wb3md3x_qcvjnnqqhb/T/pip-build-env-586ggtti/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: line_profiler/_line_profiler.pyx
  error: subprocess-exited-with-error
```

**Comment by playpauseandstop** [comment]
Can confirm similar behaviour, when trying to install `line-profiler@4.0.2` via `poetry` on my Mac M1.

**Comment by Theelx** [comment]
This is related to Cython's b1, and fixed in my latest PR. For now, you can do `pip install line_profiler "cython==3.0.0a11"`.

**Comment by tbenthompson** [comment]
Thanks for the fix Theelx!

**Comment by cjproud** [comment]
Great, thanks for the workaround guys!
