### ISSUE TITLE
Can't profile pygments itself

### ISSUE THREAD

**Issue by oprypin** [pyutils/line_profiler#41]
I was just trying to run the profiler (`kernprof -l`) on [a function](https://github.com/pygments/pygments/blob/6b615e68374a1bce04a3f258a2ce10d4a5e319de/pygments/lexers/__init__.py#L101) under 'pygments' package.

Inserting `@profile` over top of it gives `NameError: name 'profile' is not defined`.

Inserting `import line_profiler; profile = line_profiler.LineProfiler()` gives this:

```
Traceback (most recent call last):
  File "~/.local/bin/kernprof", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.9/site-packages/kernprof.py", line 202, in main
    import line_profiler
  File "~/.local/lib/python3.9/site-packages/line_profiler/__init__.py", line 10, in <module>
    from .line_profiler import __version__
  File "~/.local/lib/python3.9/site-packages/line_profiler/line_profiler.py", line 23, in <module>
    from IPython.core.magic import (Magics, magics_class, line_magic)
  File "/usr/lib/python3.9/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/usr/lib/python3.9/site-packages/IPython/terminal/embed.py", line 14, in <module>
    from IPython.core.magic import Magics, magics_class, line_magic
  File "/usr/lib/python3.9/site-packages/IPython/core/magic.py", line 20, in <module>
    from . import oinspect
  File "/usr/lib/python3.9/site-packages/IPython/core/oinspect.py", line 46, in <module>
    from pygments.lexers import PythonLexer
  File "~/.local/lib/python3.9/site-packages/pygments/lexers/__init__.py", line 102, in <module>
    profile = line_profiler.LineProfiler()
```
```
AttributeError: partially initialized module 'line_profiler' has no attribute 'LineProfiler' (most likely due to a circular import)
```

So I guess this happens because `line_profiler` has Pygments in its import tree.

**Comment by Erotemic** [comment]
Hmm, it seems this stems from the fact that we are using `line_profiler` to grab the version for `kernprof`. Maybe this is the wrong thing to do, as if we were not including line_profiler then kernprof would run fine by itself.

Versions are such a pain. If we could restrict to 3.7+ this would not be a problem because we could do lazy imports in the `line_profiler` package so just grabbing the version wouldn't trigger any side effects of invoking IPython.

FWIW if you hack kernprof.py to replace lines:

```

try:
    from line_profiler import __version__
except ImportError:
    __version__ = 'UNKNOWN'
```

with 

```
 __version__ = 'UNKNOWN'
```

that should work around your problem. But ultimately this is something I want to fix in this repo. I did not intend for that change to cause functionality regression. 

I think what I will do is in the branch for 3.2.2, I'll simply make kernprof maintain its own version, and in the CI scripts I can assert that the version for kernprof and line_profiler are in sync. 

Ultimately I want a better solution. I did try versioneer, but it didn't seem to work the way I wanted. Maybe I can modify it, I'm not sure, I'm just musing. 

Merging #67 will now fix this issue.

**Comment by Nodd** [comment]
#67 has been merged, maybe this issue can be closed ?
