### ISSUE TITLE
UnboundLocalError when trying to install 

### ISSUE THREAD

**Issue by fpalamour** [pyutils/line_profiler#80]
I'm trying to install line_profiler inside a pypy docker container and I got the following error :

```
Collecting line_profiler
  Using cached line_profiler-3.2.6.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/pypy/bin/pypy3 /opt/pypy/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpceop50yy
       cwd: /tmp/pip-install-aazpjb6y/line-profiler_48a606e0e1814e9cace411eb40e5e062
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/opt/pypy/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/pypy/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/pypy/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-jny_9a6c/overlay/site-packages/setuptools/build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-jny_9a6c/overlay/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-jny_9a6c/overlay/site-packages/setuptools/build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-jny_9a6c/overlay/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 191, in <module>
      MB_PYTHON_TAG = native_mb_python_tag()
    File "setup.py", line 175, in native_mb_python_tag
      raise NotImplementedError(impl)
  UnboundLocalError: local variable 'impl' referenced before assignment
  ----------------------------------------
```
Looking at the code of native_mb_python_tag() in setup.py, I'd say there's no reason to declare the `impl` variable inside a condition if there's a chance to use it in the else closure.

**Comment by Erotemic** [comment]
So, it actually is trying to be used to `raise NotImplementedError(impl)`, which would fail anyway because pypy is not supported (we have compiled extensions). However, it shouldn't error with an `UnboundLocalError`, so that is a mistake.

The version of this function I usually use (when I support pypy) is: 

```
def native_mb_python_tag(plat_impl=None, version_info=None):
    """
    Get the correct manylinux python version tag for this interpreter

    Example:
        >>> print(native_mb_python_tag())
        >>> print(native_mb_python_tag('PyPy', (2, 7)))
        >>> print(native_mb_python_tag('CPython', (3, 8)))
    """
    if plat_impl is None:
        import platform
        plat_impl = platform.python_implementation()

    if version_info is None:
        import sys
        version_info = sys.version_info

    major, minor = version_info[0:2]
    if minor > 9:
        ver = '{}_{}'.format(major, minor)
    else:
        ver = '{}{}'.format(major, minor)

    if plat_impl == 'CPython':
        # TODO: get if cp27m or cp27mu
        impl = 'cp'
        if ver == '27':
            IS_27_BUILT_WITH_UNICODE = True  # how to determine this?
            if IS_27_BUILT_WITH_UNICODE:
                abi = 'mu'
            else:
                abi = 'm'
        else:
            if sys.version_info[:2] >= (3, 8):
                # bpo-36707: 3.8 dropped the m flag
                abi = ''
            else:
                abi = 'm'
        mb_tag = '{impl}{ver}-{impl}{ver}{abi}'.format(**locals())
    elif plat_impl == 'PyPy':
        abi = ''
        impl = 'pypy'
        ver = '{}{}'.format(major, minor)
        mb_tag = '{impl}-{ver}'.format(**locals())
    else:
        raise NotImplementedError(plat_impl)
    return mb_tag
```

I think it should be possible to replace the one in line-profiler with the one that handles pypy, but note that line_profiler itself won't work without the c-extensions (although I suppose kernprof.py might still work). What is your use case?

**Comment by Erotemic** [comment]
This is now merged in master and released on pypi.
